# Generated by Django 2.2.3 on 2022-09-18 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='home',
            field=models.CharField(default='Home', max_length=50),
        ),
    ]
