# Generated by Django 2.2.3 on 2022-09-19 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teams', '0002_team_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(default='Football Team', max_length=60),
        ),
    ]
