# Generated by Django 2.2.3 on 2022-09-18 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(choices=[('QB', 'Quarterback'), ('LO', 'Liniero Ofensivo'), ('C', 'Corredor'), ('CP', 'Corredor de poder'), ('TE', 'Tight End'), ('WR', 'Wide Receiver'), ('LB', 'Line Backer'), ('CB', 'Cornerback'), ('S', 'Safety'), ('K', 'Kicker'), ('P', 'Punter'), ('KR', 'Kick Returner'), ('PR', 'Punt Returner'), ('CL', 'Centro Largo')], default='Customer Service', max_length=32)),
                ('number', models.IntegerField()),
                ('status', models.BooleanField(default=True, verbose_name='Player disponibility')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teams.Team')),
            ],
        ),
    ]
