# Generated by Django 2.2.3 on 2022-09-18 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('QB', 'Quarterback'), ('LO', 'Liniero Ofensivo'), ('C', 'Corredor'), ('CP', 'Corredor de poder'), ('TE', 'Tight End'), ('WR', 'Wide Receiver'), ('LB', 'Line Backer'), ('CB', 'Cornerback'), ('S', 'Safety'), ('K', 'Kicker'), ('P', 'Punter'), ('KR', 'Kick Returner'), ('PR', 'Punt Returner'), ('CL', 'Centro Largo')], default='Corredor', max_length=32),
        ),
    ]
